export const SET_GIPHY_SEARCHTEXT ='SET_GIPHY_SEARCHTEXT';
export const SET_GIPHY_TYPE ='SET_GIPHY_TYPE';
export const SET_RESULT_ITEMS ='SET_RESULT_ITEMS';
export const SET_TRENDING_RESULTS ='SET_TRENDING_RESULTS';
export const SET_SEARCH_RESULTS ='SET_SEARCH_RESULTS';
export const SET_LOADING ='SET_LOADING';
export const SET_ERROR ='SET_ERROR';
